### ISSUE TITLE
Heroku app fail

### ISSUE THREAD

**Issue by rozbrajaczpoziomow** [eulerscheZahl/CG-Tools#1]
Simple as that
https://eulerschezahl.herokuapp.com

**Comment by eulerscheZahl** [comment]
Yes, I'm aware of that.
I received the following mail on the 22nd:
`You have used 80% of your 550 free dyno hours for October 2022. The following steps can help you keep your app running smoothly.`
And on the 27th:
```
You have used your entire allocation of 550 free dyno hours for October 2022.

Your app(s) have stopped running and will not restart until you receive more free dyno hours next month.

To keep your app(s) running smoothly, consider [upgrading to Hobby dynos](https://hello.heroku.com/appsdash) for $7 per dyno per month. Your app(s) will stay live and your users will enjoy 24/7 access.
```

It will be back tomorrow. However, starting on Nov 28th Heroku will discontinue their free services. I no longer care enough to pay for the service or find a new hosting provider, therefore the puzzle search will stop working permanently.
You or anyone else are free to take the code and put it somewhere else.

**Comment by rozbrajaczpoziomow** [comment]
I'll probably just self-host it for local use then, thanks!

**Comment by eulerscheZahl** [comment]
In that case you'll need a lvl29+ account on CodinGame to access the list of approved puzzles.
There's an update script which I haven't published before: https://github.com/eulerscheZahl/CG-Tools/blob/master/update_puzzles.py - I run this on startup of my PC to keep the list up to date.

**Comment by rozbrajaczpoziomow** [comment]
Thanks for the help!
https://i.imgur.com/vit3Ngs.png Time to go and do some puzzles then.
